run_name: OLMo-1B-a100-0501v2
# SCRATCH_DIR: /mnt/zzb6data/peixunban/zzb6/home/swZheng/OLMo/tmp/output-test
seed: 61980                           # 随机数种子，用于确保实验可复现
dry_run: false                      # 是否为试运行模式，若为 true 不会真正训练

wandb:
  name: ${run_name}
  project: olmo-a100-0501
  entity: zhengshui13

# 模型配置
model:
  d_model: 2048 #模型维度
  n_heads: 16    #注意力头数
  n_layers: 16   #Transformer 层数
  mlp_ratio: 8   # 前馈网络的维度
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: true  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 1024
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0  # 注意, 需要与tokenizer中的词表一致
  pad_token_id: 1  # 注意, 需要与tokenizer中的词表一致
  init_device: cuda     #这里如何修改？
  init_fn: normal     #这里如何修改？

compile: ##null  # causes instability on AMD GPUs
  backend: inductor   # Inductor 是 PyTorch 2.0 中引入的一个 编译后端，它用于优化模型的计算图，目的是加速训练和推理过程。

# 优化器配置
optimizer:
  name: adamw
  learning_rate: 1.0e-4 
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

# tokenizer配置
tokenizer:
  identifier: tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right

# checkpoint保存配置
# save_folder: ${path.choose:${oc.env:SCRATCH_DIR,no_exist}/checkpoints,/results}/${oc.env:SLURM_JOB_ID,${run_name}}
# save_folder: ${
#   path.choose:
#     ${oc.env:SCRATCH_DIR,no_exist}/checkpoints,
#     /results
#   }/${oc.env:SLURM_JOB_ID,${run_name}}
save_folder: /mnt/zzb6data/peixunban/zzb6/home/swZheng/OLMo/tmp/output-1B
save_overwrite: true
# Sharded checkpoints (best for restarts)
save_interval: 1000    # 1000步保存一次
save_num_checkpoints_to_keep: 5   # 保留最近3个step
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 3000    # 保留完成的模型，3000步保存一次
save_num_unsharded_checkpoints_to_keep: -1    #保存所有unshared model, 如果是3保存最近3个

# checkpoint加载路径
load_path: null
  #'/mnt/geogpt-gpfs/llm-course/home/yly/OLMo/checkpoints/OLMo-1B/step1000/'
  # /mnt/zzb6data/peixunban/zzb6/home/swZheng/OLMo/tmp/checkpoints-1024-512-8/step600

# 训练步数及batchsize
max_duration: 739_328  # 3.1T tokens
# max_duration: 86400  # 24hours。 3.1T tokens------------------？
global_train_batch_size: 640   # 512  
device_train_microbatch_size: 20 #16 

precision: amp_bf16

fsdp:
  wrapping_strategy: null
  precision: mixed
  sharding_strategy: SHARD_GRAD_OP  #FSDP 中的一种梯度分片策略

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

# 训练时长
time_limit: 864000

# 验证集地址
eval_interval: ${save_interval}
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  # lump all the small datasets together (we still get separate metrics).
  - label: v3-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v3-small-c4_en-validation:
          - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
        v3-small-dolma_books-validation:
          - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/dolma_books/val/part-0-00000.npy
        v3-small-dolma_common-crawl-validation:
          - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/dolma_common-crawl/val/part-0-00000.npy
        v3-small-dolma_pes2o-validation:
          - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/dolma_pes2o/val/part-0-00000.npy
        v3-small-dolma_reddit-validation:
          - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/dolma_reddit/val/part-0-00000.npy
        v3-small-dolma_stack-validation:
          - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/dolma_stack/val/part-0-00000.npy
        v3-small-dolma_wiki-validation:
          - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/dolma_wiki/val/part-0-00000.npy
        v3-small-ice-validation:
          - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/ice/val/part-0-00000.npy
        # v3-small-m2d2_s2orc-validation:
        #   - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/m2d2_s2orc/val/part-0-00000.npy
        # v3-small-pile-validation:
        #   - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/pile/val/part-0-00000.npy
        # v3-small-wikitext_103-validation:
        #   - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v3_small_gptneox20b/wikitext_103/val/part-0-00000.npy

  - label: v2-small-ppl-validation
    data:
      num_workers: 8
      drop_last: true
      datasets:
        v2-small-4chan-validation:
        - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/4chan/val.npy
        v2-small-c4_100_domains-validation:
        - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/c4_100_domains/val.npy
        v2-small-c4_en-validation:
        - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/c4_en/val.npy
        v2-small-gab-validation:
        - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/gab/val.npy
        v2-small-ice-validation:
        - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/ice/val.npy
        v2-small-m2d2_s2orc-validation:
        - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/m2d2_s2orc/val.npy
        v2-small-m2d2_wiki-validation:
        - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/m2d2_wiki/val.npy
        v2-small-manosphere-validation:
        - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/manosphere/val.npy
        # v2-small-mc4_en-validation:
        # - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/mc4_en/val.npy
        # v2-small-pile-validation:
        # - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/pile/val.npy
        # v2-small-ptb-validation:
        # - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/ptb/val.npy
        # v2-small-twitterAEE-validation:
        # - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/twitterAEE/val.npy
        # v2-small-wikitext_103-validation:
        # - /mnt/zzb6data/peixunban/zzb6/home/sfx/eval-data/perplexity/v2_small_gptneox20b/wikitext_103/val.npy

  # 声明对验证集所要执行的测试任务
  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream

  # - label: boolq  # requires implemention of the pmi_dc matrix
    # type: downstream

  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  # - label: arc_challenge  # requires implemention of the pmi_dc matrix
  #   type: downstream

  - label: copa
    type: downstream

  - label: rte
    type: downstream

  - label: commitment_bank
    type: downstream

  - label: mrpc
    type: downstream

  - label: sst2
    type: downstream

# 训练数据位置
data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  paths:
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-10-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-18-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-07-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-01-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-03-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-04-00004.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-13-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-17-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-09-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-04-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-00-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-11-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-02-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-07-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-06-00005.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-06-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-01-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-08-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-02-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-11-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-15-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-06-00004.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-08-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-05-00001.npy
    # - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-00-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-16-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-12-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-08-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-12-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-02-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-09-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-17-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-13-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-15-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-13-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-05-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-19-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-14-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-02-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-07-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-02-00004.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-14-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-08-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-15-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-10-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-06-00006.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-17-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-04-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-00-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-06-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-00-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-09-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-11-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-10-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-09-00000.npy
    # - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-01-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-05-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-14-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-16-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-10-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-08-00004.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-08-00005.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-06-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-05-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-10-00004.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-13-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-02-00005.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-04-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-06-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-03-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-14-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-03-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer1/part-04-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-10-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-01-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-05-00004.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-00-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-07-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-06-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-02-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-15-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-08-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-05-00001.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-12-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-17-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-13-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-05-00002.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-14-00000.npy
    # - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-11-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-09-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-05-00003.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-16-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-05-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-03-00000.npy
    - /mnt/zzb6data/peixunban/zzb6/data/zjf_zsw/tokenizer2/part-04-00000.npy

